nngn:entities():set_max(1 << 20)
nngn:animations():set_max(1 << 16)
nngn:graphics():resize_textures(5)
nngn:textures():set_max(5)
nngn:renderers():set_max_sprites(1 << 16)
nngn:renderers():set_max_screen_sprites(1 << 7)
nngn:renderers():set_max_cubes(1 << 16)
nngn:renderers():set_max_voxels(1 << 16)
