nngn:entities():set_max(1 << 20)
nngn:animations():set_max(1 << 16)
nngn:graphics():resize_textures(16)
nngn:textures():set_max(16)
nngn:renderers():set_max_sprites(1 << 16)
nngn:renderers():set_max_screen_sprites(1 << 7)
nngn:renderers():set_max_translucent(1 << 7)
nngn:renderers():set_max_cubes(1 << 16)
nngn:renderers():set_max_voxels(1 << 16)
nngn:renderers():set_max_spheres(1 << 7)
nngn:renderers():set_max_text(1 << 16)
nngn:map():set_max(1 << 20)
nngn:colliders():set_max_colliders(1 << 13)
nngn:renderers():set_max_colliders(1 << 13)
nngn:colliders():set_max_collisions(1 << 13)
