#ifndef NNGN_CONST_H
#define NNGN_CONST_H

#define NNGN_TEXTURE_EXTENT 512
#define NNGN_TEXTURE_SIZE (4 * NNGN_TEXTURE_EXTENT * NNGN_TEXTURE_EXTENT)
#define NNGN_MAX_LIGHTS 8
#define NNGN_SHADOWS_ENABLED_BIT (1u << 1)
#define NNGN_LUMINANCE_MAX 9.6

#endif
